/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f7f9fc',
        'surface-dim': '#d8dadd',
        'surface-bright': '#f7f9fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f7',
        'surface-container': '#eceef1',
        'surface-container-high': '#e6e8eb',
        'surface-container-highest': '#e0e3e6',
        'on-surface': '#191c1e',
        'on-surface-variant': '#464652',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f4',
        outline: '#767684',
        'outline-variant': '#c6c5d5',
        'surface-tint': '#4b53bb',
        primary: '#4b53bb',
        'on-primary': '#ffffff',
        'primary-container': '#8b93ff',
        'on-primary-container': '#1d238f',
        'inverse-primary': '#bec2ff',
        secondary: '#006c52',
        'on-secondary': '#ffffff',
        'secondary-container': '#58f9c8',
        'on-secondary-container': '#007055',
        tertiary: '#82542a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c89161',
        'on-tertiary-container': '#502b03',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e0e0ff',
        'primary-fixed-dim': '#bec2ff',
        'on-primary-fixed': '#00016d',
        'on-primary-fixed-variant': '#3239a2',
        'secondary-fixed': '#5cfcca',
        'secondary-fixed-dim': '#34dfaf',
        'on-secondary-fixed': '#002117',
        'on-secondary-fixed-variant': '#00513d',
        'tertiary-fixed': '#ffdcc1',
        'tertiary-fixed-dim': '#f6ba87',
        'on-tertiary-fixed': '#2e1500',
        'on-tertiary-fixed-variant': '#663d15',
        background: '#f7f9fc',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e6',
      },
      fontFamily: {
        'jakarta': ['Plus Jakarta Sans', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '48px',
        'gutter': '24px',
        'margin': '32px',
      },
    },
  },
  plugins: [],
}</content>
<parameter name="filePath">e:\Projects_Local_Machine\stitch_aura_knowledge_os\stitch_aura_knowledge_os\tailwind.config.js